[toolchain]
channel = "nightly-2025-12-29"

# This specifies components explicitly in order to always include rust-analyzer.
#
# component availability by nightly version:
# https://rust-lang.github.io/rustup-components-history/
components = [
    "rustc",
    "cargo",
    "rustfmt",
    "rust-std",
    "rust-docs",
    "clippy",
    "rust-analyzer"
]
